### ISSUE TITLE
Hacking target?

### ISSUE THREAD

**Issue by mawann** [xcorp/pmd#1]
My web sites keeps getting requests for /pmd/index.php (randomly).
I suspect, the hackers thought my server was using this script. Maybe they saw a security hole.

2021/12/31 06:04:53 [error] 158952#158952: *54108 open() "_(***hidden***)_/pmd/index.php" failed (2: No such file or directory), client: 114.215.71.28, server: localhost, request: "GET /pmd/index.php HTTP/1.1", host: "_(***hidden***)_"

**Comment by xcorp** [comment]
Try googling /pmd/index.php and you will find a lot more likely candidates than this 10 year old project I never deployed anywhere.
